<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MTSPVRR" failures="2" tests="9" name="TestNG RetryLogic" time="0.041" errors="0" timestamp="2022-12-24T19:34:53 EST">
  <testcase classname="com.retryLogic.Test.RetryLogicTestCases" name="Test1" time="0.006">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.retryLogic.Test.RetryLogicTestCases" name="Test1" time="0.0">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.retryLogic.Test.RetryLogicTestCases" name="Test1" time="0.0">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.retryLogic.Test.RetryLogicTestCases" name="Test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.retryLogic.Test.RetryLogicTestCases.Test1(RetryLogicTestCases.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="com.retryLogic.Test.RetryLogicTestCases" name="Test2" time="0.0"/>
  <testcase classname="com.retryLogic.Test.RetryLogicTestCases" name="Test3" time="0.001">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="com.retryLogic.Test.RetryLogicTestCases" name="Test3" time="0.001">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="com.retryLogic.Test.RetryLogicTestCases" name="Test3" time="0.0">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="com.retryLogic.Test.RetryLogicTestCases" name="Test3" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.retryLogic.Test.RetryLogicTestCases.Test3(RetryLogicTestCases.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
</testsuite> <!-- TestNG RetryLogic -->
